// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKggDAuayGWzgvfcrwjSZWCJ-BTD7fd1E',
    appId: '1:989836224616:web:18ba8b21253702977573dd',
    messagingSenderId: '989836224616',
    projectId: 'flutter-app-9624c',
    authDomain: 'flutter-app-9624c.firebaseapp.com',
    storageBucket: 'flutter-app-9624c.appspot.com',
    measurementId: 'G-6S6CEFRMWS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnsx3OPpd6cgICozJNkb8SudZ7_DLP2V4',
    appId: '1:989836224616:android:04615fa90cf546177573dd',
    messagingSenderId: '989836224616',
    projectId: 'flutter-app-9624c',
    storageBucket: 'flutter-app-9624c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGBcU8oqSSpIiH_qAD5VfvuJ_zWtXzUkA',
    appId: '1:989836224616:ios:dbad3bcbe258b4207573dd',
    messagingSenderId: '989836224616',
    projectId: 'flutter-app-9624c',
    storageBucket: 'flutter-app-9624c.appspot.com',
    iosBundleId: 'com.example.todoUsers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGBcU8oqSSpIiH_qAD5VfvuJ_zWtXzUkA',
    appId: '1:989836224616:ios:9f2b229f53d1de507573dd',
    messagingSenderId: '989836224616',
    projectId: 'flutter-app-9624c',
    storageBucket: 'flutter-app-9624c.appspot.com',
    iosBundleId: 'com.example.todoUsers.RunnerTests',
  );
}
